### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by milestonezero** [Throvn/MLKitPoseClassificationExample#1]
Hello, 
   Thanks for implementing this, could you please help me find the issue. I build the app and seems like some files are missing or something I am mistaken.

```
Showing Recent Messages
Unable to load contents of file list: '/Target Support Files/Pods-MLKitPoseClassificationExample/Pods-MLKitPoseClassificationExample-resources-Debug-input-files.xcfilelist'

```

**Comment by Throvn** [comment]
Hey, thanks for your interest in the repo. This looks like an issue with the MLKit dependency rather than the implementation itself. Have you run `pod install` (and then opening .xcworkspace) in the projects root directory before trying to build it? If this doesn't help, I've found this [answer](https://stackoverflow.com/questions/55011171/xcode-buildtime-error-unable-to-load-contents-of-file-list-info-plist#56125602) on stack overflow which apparently helped a lot of people with a similar issue, would you try these out and tell me if the issue persists? Also, are you on an M16 chip?

**Comment by milestonezero** [comment]
@Throvn Thank you for very quick response. I figured out later and that was the exact issue you mentioned and after pod install, issue fixed.
